#!/bin/sh

#
# Gradle start up script for POSIX generated by the Gradle wrapper.
#

set -e

APP_BASE_NAME=${0##*/}

# Resolve APP_HOME, following symlinks.
app_path=$0
while
    APP_HOME=${app_path%"${app_path##*/}"}
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in
      /*)   app_path=$link ;;
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit 1

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ ! -f "$CLASSPATH" ] ; then
    echo "ERROR: Gradle wrapper jar not found at $CLASSPATH" >&2
    exit 1
fi

# Determine the Java command to use.
if [ -n "${JAVA_HOME:-}" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
        echo "Set JAVA_HOME to a valid JDK 17+ installation." >&2
        exit 1
    fi
else
    JAVACMD=java
    if ! command -v java > /dev/null 2>&1 ; then
        echo "ERROR: JAVA_HOME is not set and no 'java' command could be found." >&2
        echo "Install JDK 17+ or set JAVA_HOME." >&2
        exit 1
    fi
fi

exec "$JAVACMD" \
    -Xmx64m -Xms64m \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
